#!/usr/bin/env python3
"""Generate board-specific Markdown guidance from machine-readable JSON data."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_BOARD_DIR = ROOT / "boards"
DEFAULT_OUTPUT_DIR = ROOT / "references" / "boards"


def load_boards(board_dir: Path) -> list[dict[str, Any]]:
    boards: list[dict[str, Any]] = []
    for path in sorted(board_dir.glob("*.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        data["_path"] = path
        boards.append(data)
    if not boards:
        raise ValueError(f"no board JSON files found in {board_dir}")
    return boards


def render_table(rows: list[dict[str, Any]]) -> list[str]:
    lines = ["| 引脚 | 功能 | 级别 | 注意事项 |", "|---|---|---|---|"]
    for row in rows:
        notes = str(row.get("notes", "")).replace("|", "\\|")
        lines.append(
            f"| {row['pin']} | {row['function']} | {row['severity']} | {notes} |"
        )
    return lines


def render_board(data: dict[str, Any]) -> str:
    lines = [
        f"# {data['name']}",
        "",
        "## 识别条件",
        "",
        data["identification"],
        "",
        data["description"],
        "",
        "## 系统引脚与板载资源",
        "",
        "下表由 `boards/" + data["id"] + ".json` 自动生成。级别为 `blocked` 的引脚不可分配，`confirm` 需要用户确认，`release` 需要先确认板载功能已释放。",
        "",
        *render_table(
            data.get("system_pins", [])
            + [
                {
                    "pin": ", ".join(item["pins"]),
                    "function": item["name"],
                    "severity": item["severity"],
                    "notes": item.get("notes", ""),
                }
                for item in data.get("peripherals", [])
            ]
        ),
        "",
    ]

    headers = data.get("expansion_headers", {})
    if headers:
        lines.extend(["## 扩展排针", ""])
        for name, pins in headers.items():
            lines.extend([f"### {name}", "", "`" + ", ".join(pins) + "`", ""])

    lines.extend([
        "## 选择引脚的规则",
        "",
        "优先排除 `blocked` 引脚；对 `confirm` 和 `release` 引脚，必须先说明板载功能和复用影响，再根据用户确认继续。自定义板的真实连接以用户原理图和当前 `.syscfg` 为准。",
        "",
        "## 验证要求",
        "",
        data["validation"],
        "",
        "<!-- Generated by scripts/generate_board_docs.py; edit boards/*.json instead. -->",
        "",
    ])
    return "\n".join(lines)


def generate(board_dir: Path, output_dir: Path, check: bool = False) -> int:
    output_dir.mkdir(parents=True, exist_ok=True)
    expected: set[Path] = set()
    changed = False
    for data in load_boards(board_dir):
        output = output_dir / f"{data['id']}.md"
        expected.add(output.resolve())
        content = render_board(data)
        current = output.read_text(encoding="utf-8") if output.exists() else None
        if current != content:
            changed = True
            if check:
                print(f"OUTDATED: {output.relative_to(ROOT)}")
            else:
                output.write_text(content, encoding="utf-8")
                print(f"Generated: {output.relative_to(ROOT)}")

    for existing in output_dir.glob("*.md"):
        if existing.resolve() not in expected and "Generated by scripts/generate_board_docs.py" in existing.read_text(encoding="utf-8"):
            changed = True
            if check:
                print(f"ORPHANED: {existing.relative_to(ROOT)}")
            else:
                existing.unlink()
                print(f"Removed: {existing.relative_to(ROOT)}")

    if check and changed:
        return 1
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--board-dir", type=Path, default=DEFAULT_BOARD_DIR)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--check", action="store_true", help="Fail if generated docs are out of date.")
    args = parser.parse_args(argv)
    try:
        return generate(args.board_dir.resolve(), args.output_dir.resolve(), args.check)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
